# Port on which the application will be available
server.port=8080

# Database
#spring.datasource.url=${DB_USERSTORYPROJ_URL}
#spring.datasource.username=${DB_USERSTORYPROJ_USER}
#spring.datasource.password=${DB_USERSTORYPROJ_PASSWORD}
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# Show or not log for each sql query
#spring.jpa.show-sql=true
# Initialize a database using JPA
#spring.jpa.generate-ddl=true
# The values create, create-drop, validate, and update basically influence how the schema tool management will manipulate the database schema at startup.
#spring.jpa.hibernate.ddl-auto=update
# Spring Boot automatically creates the database schema using the data.sql file
#spring.sql.init.mode=ALWAYS

# H2 Database
spring.datasource.url=jdbc:h2:mem:userstory;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Debug mode for testing
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.hibernate.SQL=DEBUG
